import {Component, OnInit} from '@angular/core';
import {Customer} from "../model/customer";
import {Router} from "@angular/router";

@Component({
  selector: 'app-list-customer',
  templateUrl: './list-customer.component.html',
  styleUrls: ['./list-customer.component.scss']
})
export class ListCustomerComponent implements OnInit {
  mockCustomers: Customer[]
  dataSelection: any[] = [];

  constructor(
    private router: Router
  ) {
  }

  ngOnInit(): void {
    this.mockCustomers = [
      {
        id: 1,
        name: "John Doe",
        address: "123 Main Streetd.ạhkfnl,hj,ksFEkjhniuz,rf,bhz",
        company: "ABC Company",
        phoneNumber: "123-456-7890",
        insurance: "XYZ Insurance",
        mainAccountBalance: 1000,
        promotionAccountBalance: 500,
        rewardPoints: 100,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      {
        id: 2,
        name: "Jane Smith",
        address: "456 Elm Street",
        company: "DEF Company",
        phoneNumber: "987-654-3210",
        insurance: "PQR Insurance",
        mainAccountBalance: 2000,
        promotionAccountBalance: 1000,
        rewardPoints: 200,
      },
      // Thêm các khách hàng khác tại đây nếu cần
    ];
  }
  viewBalance(id: any){
    this.router.navigate(['customers', 'balance'])
  }
}
